import type { Metadata } from 'next';

import BaseLayout from '~/components/layout/Base';

//----------------------------------------------------------------------------//

export const metadata: Metadata = {
  title: 'Static Next.js Sample',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <BaseLayout>{children}</BaseLayout>;
}
