name: CI - build and deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Node.js modules cache
        uses: actions/cache@v4
        id: restore-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Node.js dependencies
        run: npm ci
        if: steps.restore-cache.outputs.cache-hit != 'true'

      - run: npm run build:ci

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
